### ISSUE TITLE
Exception While Loading Burp Extension

### ISSUE THREAD

**Issue by arbazkiraak** [DanNegrea/PyRules#1]
Traceback (most recent call last):
  File "C:\PyRules-master\PyRules.py", line 154, in registerExtenderCallbacks
    self._code = compile(script, '<string>', 'exec')
  File "<string>", line 15
    log("
       ^
SyntaxError: no viable alternative at character '"'

	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95)
	at org.python.core.ParserFacade.parse(ParserFacade.java:205)
	at org.python.core.CompileFunction.compile(__builtin__.java:1672)
	at org.python.core.CompileFunction.compile(__builtin__.java:1648)
	at org.python.core.CompileFunction.__call__(__builtin__.java:1636)
	at org.python.core.PyObject.__call__(PyObject.java:496)
	at org.python.core.PyObject.__call__(PyObject.java:500)
	at org.python.pycode._pyx5.registerExtenderCallbacks$2(C:\Users\Arbaz Hussain\Desktop\PyRules-master\PyRules.py:169)
	at org.python.pycode._pyx5.call_function(C:\Users\Arbaz Hussain\Desktop\PyRules-master\PyRules.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$0.registerExtenderCallbacks(Unknown Source)
	at burp.lgc.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DanNegrea** [comment]
Hi,

Thanks for reporting this bug.

The quick workaroud is to edit PyUtil.py and set the vars_initial and
script_initial variable to an empty string. Then load the extension again.

Hope that works for you.
Dan

**Comment by DanNegrea** [comment]
Solved with version 0.3
